package group6;

import handler.*;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultEditorKit;

public class mainFrame extends javax.swing.JFrame
{
    /**
     * Constructor
     */
    public mainFrame()
    {
        initComponents();

        /**
         * The code below adds the list of available fonts in the system
         */
        String[] fontList = java.awt.GraphicsEnvironment
                .getLocalGraphicsEnvironment().getAvailableFontFamilyNames();

        for (int x = 0; x < fontList.length; x++)
        {
            fontComboBox.addItem(fontList[x]);
        }

        /**
         * This sets the default selected item in the fontComboBox
         * and the sizeComboBox.
         */
        fontComboBox.setSelectedItem("Arial");
        sizeComboBox.setSelectedItem("13");

        addListeners();
        
        
        
        /**
         * The code below sets the location of the frame to the center of the
         * screen, regardless of size.
         */
        setLocationRelativeTo(this);
        
        //The code below gives the focus to the textPane.
        textPane.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        fontPane = new javax.swing.JPanel();
        fontComboBox = new javax.swing.JComboBox<>();
        sizeComboBox = new javax.swing.JComboBox<>();
        attributePane = new javax.swing.JPanel();
        boldButton = new javax.swing.JButton();
        italicButton = new javax.swing.JButton();
        underlineButton = new javax.swing.JButton();
        foregroundColorDisplay = new javax.swing.JPanel();
        foregroundColorChooser = new javax.swing.JButton();
        backgroundColorDisplay = new javax.swing.JPanel();
        backgroundColorChooser = new javax.swing.JButton();
        alignCenterButton = new javax.swing.JButton();
        alignLeftButton = new javax.swing.JButton();
        alignRightButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        printMenuItem = new javax.swing.JMenuItem();
        seperator = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem(new DefaultEditorKit.CutAction());
        copyMenuItem = new javax.swing.JMenuItem(new DefaultEditorKit.CopyAction());
        pasteMenuItem = new javax.swing.JMenuItem(new DefaultEditorKit.PasteAction());
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Changing of font size, type, and color");
        setMinimumSize(new java.awt.Dimension(575, 200));

        panel.setBackground(new java.awt.Color(200, 200, 200));
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        textPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textPane.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        textPane.setToolTipText("");
        textPane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textPane.setDragEnabled(true);
        textPane.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(textPane);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );

        fontPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        fontPane.setFocusable(false);

        fontComboBox.setEditable(true);
        fontComboBox.setToolTipText("Selects the font to be used.");
        fontComboBox.setActionCommand("fontComboBox");

        sizeComboBox.setEditable(true);
        sizeComboBox.setMaximumRowCount(15);
        sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72" }));
        sizeComboBox.setToolTipText("Selects the size of the font.");

        javax.swing.GroupLayout fontPaneLayout = new javax.swing.GroupLayout(fontPane);
        fontPane.setLayout(fontPaneLayout);
        fontPaneLayout.setHorizontalGroup(
            fontPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        fontPaneLayout.setVerticalGroup(
            fontPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(fontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        attributePane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        boldButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        boldButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bold.png"))); // NOI18N
        boldButton.setToolTipText("Bolds the selected text.");
        boldButton.setActionCommand("boldButton");
        boldButton.setFocusable(false);

        italicButton.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        italicButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/italic.png"))); // NOI18N
        italicButton.setToolTipText("Italizes the selected text.");
        italicButton.setActionCommand("italicButton");
        italicButton.setFocusable(false);

        underlineButton.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        underlineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/underline.png"))); // NOI18N
        underlineButton.setToolTipText("Underlines the selected text.");
        underlineButton.setActionCommand("underlineButton");
        underlineButton.setFocusable(false);

        foregroundColorDisplay.setBackground(new java.awt.Color(0, 0, 0));
        foregroundColorDisplay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        foregroundColorDisplay.setFocusable(false);

        foregroundColorChooser.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        foregroundColorChooser.setText("Foreground");
        foregroundColorChooser.setToolTipText("Changes the text's foreground color.");
        foregroundColorChooser.setActionCommand("foregroundButton");
        foregroundColorChooser.setFocusable(false);
        foregroundColorChooser.setOpaque(false);

        javax.swing.GroupLayout foregroundColorDisplayLayout = new javax.swing.GroupLayout(foregroundColorDisplay);
        foregroundColorDisplay.setLayout(foregroundColorDisplayLayout);
        foregroundColorDisplayLayout.setHorizontalGroup(
            foregroundColorDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foregroundColorDisplayLayout.createSequentialGroup()
                .addComponent(foregroundColorChooser)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        foregroundColorDisplayLayout.setVerticalGroup(
            foregroundColorDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foregroundColorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        foregroundColorChooser.getAccessibleContext().setAccessibleDescription("");

        backgroundColorDisplay.setBackground(new java.awt.Color(255, 255, 255));
        backgroundColorDisplay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backgroundColorDisplay.setFocusable(false);

        backgroundColorChooser.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        backgroundColorChooser.setText("Background");
        backgroundColorChooser.setToolTipText("Change the text's background color.");
        backgroundColorChooser.setActionCommand("backgroundButton");
        backgroundColorChooser.setFocusable(false);
        backgroundColorChooser.setOpaque(false);

        javax.swing.GroupLayout backgroundColorDisplayLayout = new javax.swing.GroupLayout(backgroundColorDisplay);
        backgroundColorDisplay.setLayout(backgroundColorDisplayLayout);
        backgroundColorDisplayLayout.setHorizontalGroup(
            backgroundColorDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundColorDisplayLayout.createSequentialGroup()
                .addComponent(backgroundColorChooser)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundColorDisplayLayout.setVerticalGroup(
            backgroundColorDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundColorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        alignCenterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/align_center.png"))); // NOI18N
        alignCenterButton.setToolTipText("Aligns text to the center.");
        alignCenterButton.setActionCommand("alignCenter");
        alignCenterButton.setFocusable(false);

        alignLeftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/align_left.png"))); // NOI18N
        alignLeftButton.setToolTipText("Aligns text to the left.");
        alignLeftButton.setActionCommand("alignLeft");
        alignLeftButton.setFocusable(false);

        alignRightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/align_right.png"))); // NOI18N
        alignRightButton.setToolTipText("Aligns text to the right.");
        alignRightButton.setActionCommand("alignRight");
        alignRightButton.setFocusable(false);

        javax.swing.GroupLayout attributePaneLayout = new javax.swing.GroupLayout(attributePane);
        attributePane.setLayout(attributePaneLayout);
        attributePaneLayout.setHorizontalGroup(
            attributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attributePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(italicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underlineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foregroundColorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backgroundColorDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alignLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alignCenterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alignRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        attributePaneLayout.setVerticalGroup(
            attributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foregroundColorDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(backgroundColorDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attributePaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(attributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(italicButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(underlineButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boldButton)))
            .addGroup(attributePaneLayout.createSequentialGroup()
                .addGroup(attributePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alignRightButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alignLeftButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alignCenterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fileMenu.setText("File");

        printMenuItem.setText("Print...");
        printMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                printMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(printMenuItem);
        fileMenu.add(seperator);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('K');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('V');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('K');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('K');
        pasteMenuItem.setText("Paste");
        pasteMenuItem.setToolTipText("");
        editMenu.add(pasteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About this program...");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(attributePane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fontPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(attributePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method adds functionality to buttons in the mainFrame.
     */
    private void addListeners()
    {
        styleHandler styleH = new styleHandler();
        
        boldButton.addActionListener(styleH);
        italicButton.addActionListener(styleH);
        underlineButton.addActionListener(styleH);

        foregroundColorChooser.addActionListener(new colorChooserHandler(textPane, foregroundColorDisplay));
        backgroundColorChooser.addActionListener(new colorChooserHandler(textPane, backgroundColorDisplay));

        fontComboBox.addActionListener(new fontComboBoxHandler(textPane, fontComboBox));
        sizeComboBox.addActionListener(new sizeComboBoxHandler(sizeComboBox, textPane));

        alignLeftButton.addActionListener(new alignHandler(textPane));
        alignCenterButton.addActionListener(new alignHandler(textPane));
        alignRightButton.addActionListener(new alignHandler(textPane));
    }

    /**
     * This confirms the user that they are quitting.
     */
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitMenuItemActionPerformed
    {//GEN-HEADEREND:event_exitMenuItemActionPerformed
        int exit = JOptionPane.showConfirmDialog(null, "Are you sure to exit the application?", "Exit", JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * This launches the aboutProgram
     */
    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutMenuItemActionPerformed
    {//GEN-HEADEREND:event_aboutMenuItemActionPerformed
        new aboutProgramDialog(this, true).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * Printing capability
     */
    private void printMenuItemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printMenuItemActionPerformed
    {//GEN-HEADEREND:event_printMenuItemActionPerformed
        try
        {
            boolean doPrint = textPane.print();
            if (doPrint)
            {
                JOptionPane.showMessageDialog(null, "Printing is done.");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error while printing.");
        }
    }//GEN-LAST:event_printMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton alignCenterButton;
    private javax.swing.JButton alignLeftButton;
    private javax.swing.JButton alignRightButton;
    private javax.swing.JPanel attributePane;
    private javax.swing.JButton backgroundColorChooser;
    private javax.swing.JPanel backgroundColorDisplay;
    private javax.swing.JButton boldButton;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox<String> fontComboBox;
    private javax.swing.JPanel fontPane;
    private javax.swing.JButton foregroundColorChooser;
    private javax.swing.JPanel foregroundColorDisplay;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton italicButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem printMenuItem;
    private javax.swing.JPopupMenu.Separator seperator;
    private javax.swing.JComboBox<String> sizeComboBox;
    private javax.swing.JTextPane textPane;
    private javax.swing.JButton underlineButton;
    // End of variables declaration//GEN-END:variables
}
